### ISSUE TITLE
Django 1.6 and 1.7 support

### ISSUE THREAD

**Issue by chhantyal** [awesto/django-shop#281]
Wanted to use this with Django 1.7, looks like it only supports till 1.5. Please specify this in docs or support latest Django release.

**Comment by vivazzi** [comment]
Django-shop has dependence south, so django 1.8 show error: "There is no South database module 'south.db.postgresql_psycopg2' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS".
The problem is solved with removing of south from lib.
Please, fix dependences.

**Comment by priyaPromact** [comment]
Django-shop when used with django 1.7 or above give this error:
 File "/home/vagrant/local/lib/python2.7/site-packages/shop/models_bases/managers.py", line 93, in OrderManager
    @transaction.commit_on_success
AttributeError: 'module' object has no attribute 'commit_on_success'
 
This can be fixed by by replacing @transaction.commit_on_success to @transaction.atomic in the above mentioned file.
Please fix this issue.

**Comment by jrief** [comment]
The new django-shop only work with Django-1.7 and upwards.
Its still under development, but available here:
https://github.com/jrief/django-shop

**Comment by jrief** [comment]
Closed. Please check version 0.9.
